# 1. 넘파이 (NumPy : Numerical Python)

In [1]:
import numpy as np

## 1-1. ndarray 데이터 확인
- ndarray.shape : ndarray의 (행의 수, 열의 수) 튜플
- ndarray.ndim : ndarray 차원
- ndarray.dtype : ndarray 내 데이터 타입
- ndarray.astype(*'data_type'*)
- python type(*data*) : data의 데이터 타입

## 1-2. 데이터 세트 선택 (Indexing) : [ ]
- 단일값 추출: [*index*]
- Slicing : [*start*:*stop*:*step*]
- Boolean Indexing : [*Boolean Condition*]
- Fancy Indexing : [*list of index*]
- index, start, end의 값이 음수인 경우 배열의 뒤에서부터 indexing

### Slicing : [*start*:*stop*:*step*]

In [2]:
# array1에 0부터 11까지의 1차원 배열 생성
array1 = np.arange(10)
print(array1)

# 앞에서 3개 요소 반환
print(array1[:3])

# 앞에서 3번째부터 마지막 요소까지 반환
print(array1[2:])

# 전체 반환
print(array1[:].copy())
print(array1[:].copy())

# 뒤에서 3번째 부터 반환
print(array1[-3::])

# 앞에서부터 뒤에서 3번째 요소까지 반환
print(array1[:-2])

# 뒤에서부터 모두 반환

print(array1[::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[7 8 9]
[0 1 2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]

### Boolean Indexing : [*Boolean Condition*]

In [3]:
array1d = np.arange(start=1, stop=10)
# 5보다 큰 값만 출력
print(array1d[array1d > 5])

# 5보다 크고 8보다 작은 값만 출력
print(array1d[(array1d > 5) & (array1d < 8)])

[6 7 8 9]
[6 7]

In [4]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]

### Fancy Indexing : [*list of index*]

In [5]:
print(array1d)
# index 5, 1, 3, 2 순서대로 데이터 출력
print(array1d[[5, 1, 3, 2]])

[1 2 3 4 5 6 7 8 9]
[6 2 4 3]

## 1-3. 정렬 : sort( )와 argsort( )

- numpy.sort(*ndarray*, axis=) : 원 행렬 변경없음 → 반환값 활용
- ndarray.sort() : 원 행렬 변경 → 반환값 없음
- numpy.argsort(*ndarray*) : 정렬 시의 index 순서 반환

In [6]:
org_array = np.array([ 3, 1, 9, 5])
print(f'원본 행렬{org_array}')

# np.sort( )로 정렬 후 원 행렬과 반환값 출력
sort_array1 = np.array(org_array)
print(f'np.sort() 호출 후 원본 행렬 {org_array}')
print(f'np.sort() 호출 후 반환된 정렬 행렬: {sort_array1}')

# ndarray.sort( )로 정렬 후 원 행렬과 반환값 출력
#sort_array2 = org_array.sort()
#print(f'원 행렬: {sort_array2}')

# no.argsort()로 인덱스만 반환
sort_indices = np.argsort(org_array)
print(sort_indices)

# 내림차순으로 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

# index만 정렬
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

원본 행렬[3 1 9 5]
np.sort() 호출 후 원본 행렬 [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [3 1 9 5]
[1 0 3 2]
[9 5 3 1]
[2 3 0 1]

#### [연습문제] 이름과 성적이 각각의 ndarray로 주어진 경우 이름을 성적 순서로 출력하기

In [7]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sorted_score_index = np.argsort(score_array)[::-1]
print(sorted_score_index)

print(name_array[sorted_score_index])

[3 1 4 2 0]
['Kate' 'Mike' 'Samuel' 'Sarah' 'John']

# 2. 판다스 (Pandas)
#### DataFrame 기반 데이터 핸들링

In [8]:
import pandas as pd

## 2-1. 파일을 DataFrame으로 로딩
- pandas.read_csv(*file_path/url*, sep=, encoding=, ...)
- pandas.read_json(*file_path/url*, encoding=, ...)

In [9]:
# sample_data.csv 로딩
sample_df = pd.read_csv('./data/sample_data.csv')
sample_df

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago
4   Edward   NaN      M      Houston
5    Alice  24.0      F     New York
6    Susan  32.0      F      Houston

## 2-2. 데이터 확인을 위한 속성 및 메서드
- dataframe.head(*num_row=5*) : 앞 부분 출력
- dataframe.tail(*num_row=5*) : 뒷 부분 출력
- dataframe.shape : 행, 렬의 크기
- dataframe.info() : 데이터 갯수, null값(결측치, NaN) 등 확인
- python len(*dataframe*) : 데이터 갯수
- dataframe.describe() : 기술 통계값
  - 데이터형이 float나 int인 열에만 적용
  - 각 열의 개수(count), 평균(mean), 표준편차(std), 최솟값(min), 최댓값(max) 등의 통계치 확인 가능
- dataframe.value_counts(dropna=True) : 속성값별 갯수

In [10]:
# 앞부분 3열
sample_df.head(3)

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN

In [11]:
# 뒷부분 3열
sample_df.tail(3)

     Name   Age Gender      City
4  Edward   NaN      M   Houston
5   Alice  24.0      F  New York
6   Susan  32.0      F   Houston

In [12]:
# 크기, 갯수, 결측치 확인
print(sample_df.shape, len(sample_df))
sample_df.info()

(7, 4) 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     5 non-null      float64
 2   Gender  7 non-null      object
 3   City    6 non-null      object
dtypes: float64(1), object(3)
memory usage: 352.0+ bytes

In [13]:
# 기술 통계 확인
sample_df.describe()

             Age
count   5.000000
mean   26.200000
std     4.147288
min    22.000000
25%    24.000000
50%    24.000000
75%    29.000000
max    32.000000

In [14]:
# 특정 컬럼의 값 범위와 갯수 확인
# 'City' 값 범위와 갯수
print(sample_df['City'].value_counts())
# sample_df.City.value_counts()
# sample_df['City2'] = sample_df.City

# null값까지 포함하여 확인
sample_df['City'].value_counts(dropna=False)

City
New York       2
Houston        2
Los Angeles    1
Chicago        1
Name: count, dtype: int64

City
New York       2
Houston        2
Los Angeles    1
NaN            1
Chicago        1
Name: count, dtype: int64

## 2-3. DataFrame 생성 : pd.DataFrame()
    * pd.DataFrame(*list/ndarray*, columns=)
    * pd.DataFrame(*dictionary*)
        * Key는 컬럼명으로 매핑, Value는 리스트 형(또는 ndarray)

## 2-4. 결측치 처리하기
* 결측치 확인 : info(), isnull()
* 결측치 포함 행 삭제 : dataframe.dropna(subset=, inplace=)
    - subset = *List* (지정 된 범위에 null이 있을 경우 Row 삭제)
* 새로운 값으로 채우기 : dataframe.fillna(value, inplace=)
   * 특정 컬럼에 해당하는 값만 채우려는 경우 : DataFrame **[** *name* **]**.**fillna**(...)

In [15]:
# sample_data.csv을 dataframe으로 로딩하여 결측치 확인
sample_df = pd.read_csv('./data/sample_data.csv')
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     5 non-null      float64
 2   Gender  7 non-null      object
 3   City    6 non-null      object
dtypes: float64(1), object(3)
memory usage: 352.0+ bytes

In [16]:
# 결측치 확인 : 컬럼별 결측치 갯수 계산
sample_df.isnull().sum()

Name      0
Age       2
Gender    0
City      1
dtype: int64

In [17]:
# 결측치가 있는 행 추출 
sample_df[sample_df.City.isnull()]

      Name   Age Gender City
2  Charlie  22.0      M  NaN

In [18]:
# 결측치가 있는 행 삭제
sample_df.dropna(subset=['City', 'Age'])

    Name   Age Gender      City
0  Alice  24.0      F  New York
3  David  29.0      M   Chicago
5  Alice  24.0      F  New York
6  Susan  32.0      F   Houston

In [19]:
# 실제 데이터를 가져와서 삭제
sample_df.dropna(subset=['City','Age'], inplace=True)
sample_df

    Name   Age Gender      City
0  Alice  24.0      F  New York
3  David  29.0      M   Chicago
5  Alice  24.0      F  New York
6  Susan  32.0      F   Houston

## 2-5. 중복값 처리하기
* 중복값 확인 : duplicated(keep=)
    - keep = True (첫번째 미포함)
* 중복값 삭제 : drop_duplicates(subset=, inplace=)
    - subset = *List* (지정 된 범위에 null이 있을 경우 Row 삭제)

In [20]:
# index 조정
sample_df.reset_index()

   index   Name   Age Gender      City
0      0  Alice  24.0      F  New York
1      3  David  29.0      M   Chicago
2      5  Alice  24.0      F  New York
3      6  Susan  32.0      F   Houston

In [21]:
sample_df = pd.read_csv('./data/sample_data.csv')
sample_df.dropna(inplace=True)
sample_df

    Name   Age Gender      City
0  Alice  24.0      F  New York
3  David  29.0      M   Chicago
5  Alice  24.0      F  New York
6  Susan  32.0      F   Houston

In [22]:
sample_df.reset_index(drop=True, inplace=True)
sample_df

    Name   Age Gender      City
0  Alice  24.0      F  New York
1  David  29.0      M   Chicago
2  Alice  24.0      F  New York
3  Susan  32.0      F   Houston

In [23]:
# 중복값인 행 확인
sample_df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [24]:
# 중복값인 행 추출
sample_df[sample_df.duplicated(keep=False)]

    Name   Age Gender      City
0  Alice  24.0      F  New York
2  Alice  24.0      F  New York

In [25]:
# 중복값인 행 삭제
sample_df.drop_duplicates(inplace=True)

In [26]:
sample_df

    Name   Age Gender      City
0  Alice  24.0      F  New York
1  David  29.0      M   Chicago
3  Susan  32.0      F   Houston

## 2-6. 컬럼 생성, 수정, 삭제
* dataframe['컬럼명'] = data
* dataframe['컬럼명'] = dataframe 컬럼 간 연산
* drop(*컬럼명 리스트*, axis=1, inplace=)

In [33]:
# 'Age' 칼럼의 값에 모두 10을 곱한 'Age_by_10' 칼럼 생성
sample_df['Age_by_10'] = sample_df.Age *10
sample_df['temp'] = 100
sample_df

    Name   Age Gender      City  Age_by_10  temp
0  Alice  24.0      F  New York      240.0   100
1  David  29.0      M   Chicago      290.0   100
3  Susan  32.0      F   Houston      320.0   100

In [38]:
# 'temp' 컬럼 삭제
sample_df.drop('temp', axis=1, inplace=True)

## 2-7. 정렬

* dataframe.sort_values(by=컬럼리스트, ascending=True/False)

In [47]:
# 'City' 정보를 기준으로 정렬
sample_df = pd.read_csv('./data/sample_data.csv')
sample_df.sort_values(by=['Age'], ascending=False)

      Name   Age Gender         City
6    Susan  32.0      F      Houston
3    David  29.0      M      Chicago
0    Alice  24.0      F     New York
5    Alice  24.0      F     New York
2  Charlie  22.0      M          NaN
1      Bob   NaN      M  Los Angeles
4   Edward   NaN      M      Houston

## 2-8. 데이터 선택

### [ ] 연산자
    - 칼럼명 : 컬럼 선택
    - Slicing : 행 slicing만 가능
    - Boolean Indexing : 행 데이터 추출만 가능
    - 행 번호 지정 불가
### loc[*행 index*,  *칼럼명*] 연산자
    - 명칭(label) 기반 indexing
        - indexing에 label 사용
        - 행 index에 label이 없는 경우 숫자를 label로 사용
    - Slicing, Boolean Indexing
    - Slicing에 컬럼명을 사용해야함
### iloc[*행 indexing 값*, *열 indexing 값*] 연산자
    - 위치(integer location) 기반 indexing
    - Slicing, Boolean Indexing

In [53]:
sample_df[1:2]

  Name  Age Gender         City
1  Bob  NaN      M  Los Angeles

In [62]:
# 'Name' 칼럼 출력
sample_df['Name']
sample_df.Name

0      Alice
1        Bob
2    Charlie
3      David
4     Edward
5      Alice
6      Susan
Name: Name, dtype: object

In [64]:
# 'Name', 'Gender' 칼럼 출력
sample_df[['Name','Gender']]

      Name Gender
0    Alice      F
1      Bob      M
2  Charlie      M
3    David      M
4   Edward      M
5    Alice      F
6    Susan      F

In [67]:
sample_df.loc['Name':'Gender']
# 에러 샘플

Empty DataFrame
Columns: [Name, Age, Gender, City]
Index: []

In [68]:
# 1행부터 3행까지 출럭
sample_df[1:4]

      Name   Age Gender         City
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
3    David  29.0      M      Chicago

In [72]:
# Bob에 대한 정보 출력
sample_df[1:2]
sample_df[sample_df.Name=='Bob']

  Name  Age Gender         City
1  Bob  NaN      M  Los Angeles

In [78]:
# Bob의 나이 확인
# sample_df[sample_df.Name=='Bob'].Age
#
sample_df.loc[sample_df.Name=='Bob', 'Age']

1   NaN
Name: Age, dtype: float64

In [93]:
# Alice와 Susan의 이름, 나이, 성별 확인
sample_df.loc[(sample_df.Name=='Alice')|(sample_df.Name=='Susan'),['Name','Age','Gender']]

    Name   Age Gender
0  Alice  24.0      F
5  Alice  24.0      F
6  Susan  32.0      F

In [92]:
# 나이가 25세 넘는 사람
sample_df.loc[sample_df.Age > 25]

    Name   Age Gender     City
3  David  29.0      M  Chicago
6  Susan  32.0      F  Houston

In [94]:
# 나이가 25세 넘는 사람들의 이름, 나이, 도시
sample_df.loc[sample_df.Age > 25, ['Name','Age','City']]

    Name   Age     City
3  David  29.0  Chicago
6  Susan  32.0  Houston